1. Write a Python Program to Add Two Matrices?

In [11]:
a=[[1,2],
   [3,4],
   [5,6]]

In [12]:
a

[[1, 2], [3, 4], [5, 6]]

In [9]:
b=[[7,8],[9,10],[11,12]]

In [10]:
b

[[7, 8], [9, 10], [11, 12]]

In [16]:
import numpy as np

In [18]:
np.add(a,b)

array([[ 8, 10],
       [12, 14],
       [16, 18]])

2. Write a Python Program to Multiply Two Matrices?

In [20]:
np.multiply(a,b)

array([[ 7, 16],
       [27, 40],
       [55, 72]])

3. Write a Python Program to Transpose a Matrix?

In [22]:
a

[[1, 2], [3, 4], [5, 6]]

In [23]:
np.transpose(a)

array([[1, 3, 5],
       [2, 4, 6]])

4. Write a Python Program to Sort Words in Alphabetic Order?

In [37]:
list1=['a','d','g','c']

In [38]:
list1

['a', 'd', 'g', 'c']

In [39]:
np.sort(list1)

array(['a', 'c', 'd', 'g'], dtype='<U1')

5. Write a Python Program to Remove Punctuation From a String?